version: '3.5'
services:
    gateway:
        image: carlos_ferreira_ramilo/gateway-process
        container_name: gateway
        restart: always
        ports:
            - 3001:3001
            - 3002:3002
        networks:
            jscodenet:
                aliases:
                    - gateway
    
    db-0:
        image: carlos_ferreira_ramilo/db-process
        container_name: db-0
        restart: always
        networks:
            jscodenet:
                aliases:
                    - db-0
        environment:
            - SOCKET_SERVER_URL=ws://gateway:3002
            - DB_INSTANCE_ID=db-0

    db-1:
        image: carlos_ferreira_ramilo/db-process
        container_name: db-1
        restart: always
        networks:
            jscodenet:
                aliases:
                    - db-1
        environment:
            - SOCKET_SERVER_URL=ws://gateway:3002
            - DB_INSTANCE_ID=db-1

    db-2:
        image: carlos_ferreira_ramilo/db-process
        container_name: db-2
        restart: always
        networks:
            jscodenet:
                aliases:
                    - db-2
        environment:
            - SOCKET_SERVER_URL=ws://gateway:3002
            - DB_INSTANCE_ID=db-2

networks:
    jscodenet:
        name: jscodenet